#ifndef DEF_CONST
#define DEF_CONST 1

// VGA COLORS
#define BLACK 0
#define BLUE 1
#define GREEN 2
#define CYAN 3
#define RED 4
#define MAGENTA 5
#define BROWN 6
#define LIGHT_GRAY 7
#define DARK_GRAY 8
#define LIGHT_BLUE 9
#define LIGHT_GREEN 10
#define LIGHT_CYAN 11
#define LIGHT_RED 12
#define LIGHT_MAGENTA 13
#define YELLOW 14
#define WHITE 15

// PIECES ORIENTATIONS
#define CW_0 0
#define CW_90 1
#define CW_180 2
#define CW_270 3

#define BLOCK_SIZE 9

#define LANE_HEIGHT 20
#define LANE_WIDTH 10
#define LANE_POSX 100
#define LANE_POSY 10

#endif